server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/talkdesk}
spring.datasource.username=${DB_USER:talkdesk}
spring.datasource.password=${DB_PASSWORD:talkdesk}
spring.jackson.default-property-inclusion=always


# exception discloses internals. ZAP's baseline scan reports it.
server.error.include-stacktrace=always
server.error.include-message=always
