name: Analyze

on:
  push:
    branches:
      - main
      - week2-functional-testing
  pull_request:
    branches:
      - main
      - week2-functional-testing
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov fastapi httpx

      - name: Run tests and generate coverage
        working-directory: talkdesk
        env:
          PYTHONPATH: python
        run: |
          pytest tests/integration tests/e2e -q --cov=python/app.py --cov-branch --cov-report=xml:../coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
`

